INSERT INTO genre (genre_name)
VALUES
  ('Poesía'),
  ('Psicología'),
  ('Romance'),
  ('Ciencia Ficción'),
  ('Arte'),
  ('Biografía'),
  ('Negocios'),
  ('Chick Lit'),
  ('Infantil'),
  ('Cristiano'),
  ('Clásicos'),
  ('Comics'),
  ('Contemporáneo'),
  ('Libros de Cocina'),
  ('Crimen'),
  ('Libros Electrónicos'), 
  ('Fantasía'),
  ('Ficción'),
  ('Gay y Lesbiana'),
  ('Novelas Gráficas'),
  ('Ficción Histórica'),
  ('Historia'),
  ('Terror'),
  ('Humor y Comedia'),
  ('Manga'),
  ('Memorias'),
  ('Música'),
  ('Misterio'),
  ('No Ficción'),
  ('Paranormal'),
  ('Filosofía'),
  ('Religión'),
  ('Ciencia'),
  ('Autoayuda'),
  ('Suspense'),
  ('Espiritualidad'),
  ('Deportes'),
  ('Thriller'),
  ('Viajes'),
  ('Juvenil Adulto');
